/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AwesomeSauce;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void non_multiple_returns_number() {
        App classUnderTest = new App();
        assertEquals("1", classUnderTest.awesomeSauce("awesome", "sauce", 1));
    }

    @Test public void multiple_of_three_returns_given_string() {
        App classUnderTest = new App();
        assertEquals("awesome", classUnderTest.awesomeSauce("awesome", "sauce", 3));
    }

    @Test public void multiple_of_five_returns_given_string() {
        App classUnderTest = new App();
        assertEquals("sauce", classUnderTest.awesomeSauce("awesome", "sauce", 5));
    }
    
    @Test public void multiple_of_three_and_five_returns_given_strings() {
        App classUnderTest = new App();
        assertEquals("awesomesauce", classUnderTest.awesomeSauce("awesome", "sauce", 15));
    }
}
